apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: onlineb-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "onlineb.apps.pf-ocp48.rh-ocp-fischer.com"
